Fix/check descriptions
yxyx-github/algosim pull request #101
Opened 2023-10-06 10:21 UTC by vreoio

Duden Mentor sagt "ist ok".

2023-10-09 19:30 UTC, termitehuegel requested changes

2023-10-09 19:30 UTC, termitehuegel commented on src/main/algorithms/sort/combSort.ts
> +            Stattdessen nutzt er Elemente mit einer bestimmten Entfernung zueinander, der sogenannten Gap.
Stattdessen nutzt er => Stattdessen *vergleicht* er

2023-10-09 19:30 UTC, termitehuegel commented on src/main/algorithms/sort/quickSort.ts
> +            Alternative Pivotelemente wie beispielsweise der Median der Listenelemente, sind ebenfalls möglich.
Median der Listenelemente => Median einer Teilliste der Listenelemente

Den Median alle Listenelemente zu nehmen würde den Algorithmus Ineffizient machen, da das finden des Medians eine Laufzeitkomplexität von O(n) hat.

2023-10-10 10:02 UTC, yxyx-github requested changes

2023-10-11 11:58 UTC, vreoio commented on src/main/algorithms/sort/combSort.ts
> +            Anders als bei diesem Algorithmus vergleicht und tauscht Combsort aber nicht nur benachbarte Elemente.
?

2023-10-14 11:06 UTC, termitehuegel approved these changes

2023-10-15 08:11 UTC, yxyx-github commented on src/main/algorithms/sort/combSort.ts
> +            Anders als bei diesem Algorithmus vergleicht und tauscht Combsort aber nicht nur benachbarte Elemente.
Z.B. so: "Anders als bei diesem Algorithmus vergleicht und tauscht Combsort nicht nur benachbarte Elemente. Stattdessen vergleicht er auch Elemente in einer bestimmten Entfernung zueinander, der sogenannten Gap."

2023-10-17 09:31 UTC, merged