Feature/sort/quiz
yxyx-github/algosim pull request #112
Opened 2023-10-11 17:55 UTC by yxyx-github

2023-10-11 19:09 UTC, termitehuegel approved these changes
looks good

2023-10-11 19:13 UTC, termitehuegel requested changes

2023-10-11 19:13 UTC, termitehuegel commented on src/components/app/simulation/sort/quiz/SortingQuizQuestion.vue
> +    // TODO: extract into separate methods, e.g.: initEvaluation, initQuestion
remove TODO

2023-10-12 07:18 UTC, yxyx-github commented on src/components/app/simulation/sort/quiz/SortingQuizQuestion.vue
> +    // TODO: extract into separate methods, e.g.: initEvaluation, initQuestion
fixed

2023-10-12 12:49 UTC, termitehuegel approved these changes

2023-10-12 12:49 UTC, merged