added description for InsertionSort
yxyx-github/algosim pull request #60
Opened 2023-09-14 11:46 UTC by Krauseni

2023-09-14 11:57 UTC, vreoio approved these changes

2023-09-14 11:59 UTC, termitehuegel requested changes

2023-09-14 11:59 UTC, termitehuegel commented on src/main/algorithms/sort/insertionSort.ts
> +            InsertionSort ist ein einfacher stabiler Sortieralgorithmus, bei dem die Sortierung durch Einfügung erfolgt. Das erste Element der Liste kann als bereits sortierter
Bitte "Insertionsort" statt "InsertionSort" => für konsistenz mit Nennung an anderen Stellen

2023-09-14 11:59 UTC, termitehuegel commented on src/main/algorithms/sort/insertionSort.ts
> +            Teil betrachtet werden. InsertionSort wählt nun immer das nächste Element des unsortierten Teils aus und vergleicht es so lange mit dem bereits sortieren Teil der Liste,
... kann als sortiert betrachtet werden. - Ist hier vielleicht besser

2023-09-14 11:59 UTC, termitehuegel commented on src/main/algorithms/sort/insertionSort.ts
> +            Teil betrachtet werden. InsertionSort wählt nun immer das nächste Element des unsortierten Teils aus und vergleicht es so lange mit dem bereits sortieren Teil der Liste,
das erste Element des unsortierten Teils

2023-09-14 11:59 UTC, termitehuegel commented on src/main/algorithms/sort/insertionSort.ts
> +            bis die passende Stelle zum Einfügen gefunden wurde. Ist das passiert, erhöht sich der Anteil des sortierten Teils und es wird das nächste Element des unsortierten Teils gewählt.
Wurde die passende Stelle gefunden, wird das Element eingefügt. Anschließend ...

Bitte das Einfügen selbst nicht vergessen.

2023-09-14 11:59 UTC, termitehuegel commented on src/main/algorithms/sort/insertionSort.ts
> +            Da der Algorithmus in-place arbeitet, liegt die Speicherkomplexität bei O(1). Für eine Weiterentwicklung dieses Sortieralgorithmus siehe ShellSort.`
Einige andere Sortierverfahren bauen auf Selectionssort auf. Ein Beispiel hierfür ist zum Beispiel Shellsort.

2023-09-14 11:59 UTC, termitehuegel commented on src/main/algorithms/sort/insertionSort.ts
> +            Da der Algorithmus In-Place arbeitet, liegt die Speicherkomplexität bei O(1). Für eine Weiterentwicklung dieses Sortieralgorithmus siehe ShellSort.`
Es reicht, wenn du hier auf den Durchschnitt O(n²) eingehst und sagst, dass sortierte Listen in O(n) durchlaufen werden.

2023-09-23 11:56 UTC, termitehuegel approved these changes

2023-09-23 11:57 UTC, merged